name: Deploy develop
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp * /home/host1457312/dzhirnov.ru/htdocs/www