name: Deploy develop

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pull
        run: ../git pull origin develop
      - name: migrations
        run: php8 migrate -c db/phinx.php